# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
stylua = "johnnymorganz/stylua@0.20.0"
rojo = "rojo-rbx/rojo@7.4.1"
selene = "kampfkarren/selene@0.26.1"
wally = "UpliftGames/wally@0.3.2"
wally-package-types = "JohnnyMorganz/wally-package-types@1.3.1"
lune = "lune-org/lune@0.8.3"
